proxyconfig:
    host: "127.0.0.1"
    port: 6789

handlers:
    - name: test_one
      address: "127.0.0.1"
      port: 6790
      path: "plugin:echo"
    - name: test_two
      address: "127.0.0.1"
      port: 6791
      path: "plugin:proxy"
    - name: test_three
      path: passthrough
      address: 127.0.0.1
      port: 6792
